version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install git+https://$GH_TOKEN@github.com/squidfunk/mkdocs-material-insiders.git
      - pip install mkdocs-include-markdown-plugin
  build:
    commands:
      - mkdocs build
  post_build:
    commands:
      - aws s3 sync ./site $S3_BUCKET
