site_name: Wartales Wiki
site_description: Wartales Wiki
site_author: null

theme:
  name: material
  favicon: static/img/favicon.png
  palette:
    scheme: slate
  font: false
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.expand
    - content.tooltips
  logo: static/img/logo.jpg

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  generator: false

extra_css:
  - static/stylesheets/custom.css

use_directory_urls: false

plugins:
  - include-markdown
  - search

watch:
- partials

nav:

  - Companions:
      - "data/companions/index.md"
      - Attributes: "data/companions/attributes.md"
      - Base Classes:
        - Archer: "data/companions/archer.md"
        - Brute: "data/companions/brute.md"
        - Ranger: "data/companions/ranger.md"
        - Spearman: "data/companions/spearman.md"
        - Swordsman: "data/companions/swordsman.md"
        - Warrior: "data/companions/warrior.md"
      - Equipment: "data/companions/equipment.md"
      - Experience: "data/companions/experience.md"
      - Injuries: "data/companions/injuries.md"
      - Professions: "data/companions/professions.md"
      - Rank: "data/companions/rank.md"
      - Recruitment: "data/companions/recruitment.md"
      - Relationships: "data/companions/relationships.md"
      - Skills:
        - Weapon Skills: "data/companions/weapon_skills.md"
      - Status: "data/companions/status.md"
      - Titles: "data/companions/titles.md"
      - Traits: "data/companions/traits.md"

  - Camp:
    - "data/camp/index.md"

  - Inventory:
    - "data/inventory/index.md"
    - Armor:
      - Animal Accessories: "data/inventory/animal_accessories.md"
      - Armour Layers: "data/inventory/armour_layers.md"
      - Backpack Accessories: "data/inventory/backpack_accessories.md"
      - Belt Accessories: "data/inventory/belt_accessories.md"
      - Light Armor: "data/inventory/light_armor.md"
      - Medium Armor: "data/inventory/medium_armor.md"
      - Heavy Armor: "data/inventory/heavy_armor.md"
    - Camping Gear: "data/inventory/camping_gear.md"
    - Components: "data/inventory/components.md"
    - Consumables: "data/inventory/consumables.md"
    - Food:
      - Alcohol: "data/inventory/alcohol.md"
      - Cooked Meal: "data/inventory/cooked_meal.md"
      - Fish: "data/inventory/fish.md"
      - Food: "data/inventory/food.md"
      - Meat: "data/inventory/meat.md"
      - Vegetables: "data/inventory/vegetables.md"
      - Plants: "data/inventory/plants.md"
    - Hunt Map: "data/inventory/hunt_map.md"
    - Manual: "data/inventory/manual.md"
    - Miscellaneous: "data/inventory/miscellaneous.md"
    - Recipes: "data/inventory/recipes.md"
    - Trade Goods: "data/inventory/trade_goods.md"
    - Trinkets: "data/inventory/trinkets.md"
    - Weapons:
      - Swords: "data/inventory/swords.md"
      - Bows: "data/inventory/bows.md"
      - Maces: "data/inventory/maces.md"
      - Axes: "data/inventory/axes.md"
      - Daggers: "data/inventory/daggers.md"
      - Polearms: "data/inventory/polearms.md"
      - Shields: "data/inventory/shields.md"
      - Off-Hand: "data/inventory/offhand.md"

  - Compendium:
      - "data/compendium/index.md"
      - Knowledge: "data/compendium/knowledge.md"
      - Workshop: "data/compendium/workshop.md"
      - Anvil: "data/compendium/anvil.md"
      - Cooking Pot: "data/compendium/cooking_pot.md"
      - Apothecary Table: "data/compendium/apothecary_table.md"

  - World Map:
      - "data/world/index.md"
      - Tiltren County: "data/world/tiltren_county/index.md"
      - County of Arthes: "data/world/county_of_arthes/index.md"
      - Vertruse Province: "data/world/vertruse_province/index.md"
      - Ludern Region: "data/world/ludern_region/index.md"

  - Paths:
      - "data/paths/index.md"
      - Power and Might: "data/paths/power_and_might.md"
      - Trade and Wealth: "data/paths/trade_and_wealth.md"
      - Crime and Chaos: "data/paths/crime_and_chaos.md"
      - Mysteries and Wisdom: "data/paths/mysteries_and_wisdom.md"
